server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
